### ISSUE TITLE
URGENT UPDATE REQUIRED

### ISSUE THREAD

**Issue by noekun11** [UnMars/Prolific-Joiner#37] opened 2024-07-30 16:32 UTC
Suddenly im missing studies, I min the script shows 'study found' in red, and plays the sound and also opens app.prolific .com in the new tab, but i can see that the study is not reserved. This happened two times within a day already... please fix it @conradRz @UnMars @tommyka1 @ShaggyBro

**Comment by noekun11** [comment] 2024-07-30 17:03
> All the triggers I got today worked perfectly fine for me and one of them was maximum a couple of hours ago.. can't recreate it.

Can you please tell, whether you use cmd or powershell? and also the frequency of the scipt you use? and do you use the script multiple times simultaneously?

**Comment by noekun11** [comment] 2024-07-30 17:24
> Windows Terminal, latest Chrome, running one per VM with VPN. Frequency/settings are default on all except i changed the randomness to -4/+6

oh.. do you use vpn? is that allowed, i mean dont you think there is a risk of being banned? and by 'frequecy' i meant, how many times a day on average and how many hours? and also how many such VM's do you use simultaneously? thanks (sorry for too many questions)

**Comment by tommyka1** [comment] 2024-07-30 18:09
stop using VMs and VPNs, they are not allowed, they are very easy to detect from prolific's side (and they don't give you any extra security), and they serve no purpose. It is very likely that your reservation function doesn't work because of them. If you want to get studies at high frequencies, NEVER have 2 or more instances of the script running. Simply turn the search frequency down to 10 seconds (i have ran several tests, this frequency doesn't get you temp-banned from the API) and remove the random intervals completely (in my opinion, they serve no purpose whatsoever. If you get flagged, it will be because you're abusing the API, not because you're accessing the website at fixed intervals, since auto-refreshers also do that and they are confirmed to not be bannable by prolific staff).

**Comment by tommyka1** [comment] 2024-07-30 18:46
> > stop using VMs and VPNs, they are not allowed, they are very easy to detect from prolific's side (and they don't give you any extra security), and they serve no purpose. It is very likely that your reservation function doesn't work because of them. If you want to get studies at high frequencies, NEVER have 2 or more instances of the script running. Simply turn the search frequency down to 10 seconds (i have ran several tests, this frequency doesn't get you temp-banned from the API) and remove the random intervals completely (in my opinion, they serve no purpose whatsoever. If you get flagged, it will be because you're abusing the API, not because you're accessing the website at fixed intervals, since auto-refreshers also do that and they are confirmed to not be bannable by prolific staff).
> 
> Brother I know what I'm doing.. I'm managing multiple accounts at the same time, thats why i need the VPNs and the VMs..
> 
> The other guy is probably running multiple instances of the script on the same account and got rate-limited/putted on hold unfortunately..

my bad, i thought you were the OP and your second comment hadn't been posted yet when i commented

**Comment by noekun11** [comment] 2024-07-30 18:47
> > stop using VMs and VPNs, they are not allowed, they are very easy to detect from prolific's side (and they don't give you any extra security), and they serve no purpose. It is very likely that your reservation function doesn't work because of them. If you want to get studies at high frequencies, NEVER have 2 or more instances of the script running. Simply turn the search frequency down to 10 seconds (i have ran several tests, this frequency doesn't get you temp-banned from the API) and remove the random intervals completely (in my opinion, they serve no purpose whatsoever. If you get flagged, it will be because you're abusing the API, not because you're accessing the website at fixed intervals, since auto-refreshers also do that and they are confirmed to not be bannable by prolific staff).
> 
> Brother I know what I'm doing.. I'm managing multiple accounts at the same time, thats why i need the VPNs and the VMs..
> 
> The other guy is probably running multiple instances of the script on the same account and got rate-limited/putted on hold unfortunately..

not quite same.. i got more than 10 pounds of studies approved today, it happened for 1 times only

**Comment by tommyka1** [comment] 2024-07-30 18:50
> > stop using VMs and VPNs, they are not allowed, they are very easy to detect from prolific's side (and they don't give you any extra security), and they serve no purpose. It is very likely that your reservation function doesn't work because of them. If you want to get studies at high frequencies, NEVER have 2 or more instances of the script running. Simply turn the search frequency down to 10 seconds (i have ran several tests, this frequency doesn't get you temp-banned from the API) and remove the random intervals completely (in my opinion, they serve no purpose whatsoever. If you get flagged, it will be because you're abusing the API, not because you're accessing the website at fixed intervals, since auto-refreshers also do that and they are confirmed to not be bannable by prolific staff).
> 
> Brother I know what I'm doing.. I'm managing multiple accounts at the same time, thats why i need the VPNs and the VMs..
> 
> The other guy is probably running multiple instances of the script on the same account and got rate-limited/putted on hold unfortunately..

also, since you're going for maximum performance, i'd recommend lowering the search frequency to 10 seconds. The comments on the script are outdated. A couple of months ago, prolific changed their backend and they no longer give out API bans for frequencies >= 10 seconds. It really makes a difference

**Comment by noekun11** [comment] 2024-07-30 19:01
> > > stop using VMs and VPNs, they are not allowed, they are very easy to detect from prolific's side (and they don't give you any extra security), and they serve no purpose. It is very likely that your reservation function doesn't work because of them. If you want to get studies at high frequencies, NEVER have 2 or more instances of the script running. Simply turn the search frequency down to 10 seconds (i have ran several tests, this frequency doesn't get you temp-banned from the API) and remove the random intervals completely (in my opinion, they serve no purpose whatsoever. If you get flagged, it will be because you're abusing the API, not because you're accessing the website at fixed intervals, since auto-refreshers also do that and they are confirmed to not be bannable by prolific staff).
> > 
> > 
> > Brother I know what I'm doing.. I'm managing multiple accounts at the same time, thats why i need the VPNs and the VMs..
> > The other guy is probably running multiple instances of the script on the same account and got rate-limited/putted on hold unfortunately..
> 
> also, since you're going for maximum performance, i'd recommend lowering the search frequency to 10 seconds. The comments on the script are outdated. A couple of months ago, prolific changed their backend and they no longer give out API bans for frequencies >= 10 seconds. It really makes a difference

could you please tell me, on whivh line of code should i edit to change the frequenvy?

**Comment by noekun11** [comment] 2024-07-30 19:19
> line 240 is the randomness (-5s/+5s), and on the config file the wait_time brother

thanks brother... can you larify one last time... on config file i have to change the value from 30 to 10, and what should i do one line 240, as i can see, it's default for -5, +5?

**Comment by noekun11** [comment] 2024-07-30 19:25
> My personal settings would be something like 11 on wait_time (had on 30 before @tommyka1 said they no longer limit you on below that) and randomness i just offset it to keep the avg above everyone else (-4/+6). but none of that is necessary for it to work. Happy hunting!

thanks bro for the detailed explanation... i shall follow your method... if it's ok can you tell me what's the function of randomness here at line 240... you see, im not good at coding (just started doing C++ few days ago :) )

**Comment by noekun11** [comment] 2024-07-30 19:34
> wym?..
> 
> `random_offset = random.randint(-5, 5)` the -5 is the offset down, the 5 is the offset up.. every 30 seconds, now 11 (defined in the wait_time value on config) it either adds or subtracts 5 seconds.. I just made it (-4, 6)

yea... i got it now... thanks :)

**Comment by tommyka1** [comment] 2024-07-30 19:55
> wym?..
> 
> `random_offset = random.randint(-5, 5)` the -5 is the offset down, the 5 is the offset up.. every 30 seconds, now 11 (defined in the wait_time value on config) it either adds or subtracts 5 seconds.. I just made it (-4, 6)

i wouldn't recommend using a negative offset that can lead to a delay of less than 10 seconds. In case of an "unlucky" streak of 5 updates with less than 10 seconds of delay (very likely when you're running the script at such a large scale) you'll get rate limited for a couple of seconds (and potentially flagged)

**Comment by noekun11** [comment] 2024-07-31 02:11
@tommyka1 @ShaggyBro i tried to change the config wait time to 13 secs, and the offsets to (-3, 4) after that my script is giving an error (please see the image):
![image](https://github.com/user-attachments/assets/0bea61d1-7a5c-4a96-a240-54230c53a5f9)
I also reverted to the main settings, but same error... however my prolific account is working correctly on chrome

**Comment by noekun11** [comment] 2024-07-31 02:18
> @tommyka1 @ShaggyBro i tried to change the config wait time to 13 secs, and the offsets to (-3, 4) after that my script is giving an error (please see the image): ![image](https://private-user-images.githubusercontent.com/136774387/353666454-0bea61d1-7a5c-4a96-a240-54230c53a5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTI1MzQsIm5iZiI6MTcyMjM5MjIzNCwicGF0aCI6Ii8xMzY3NzQzODcvMzUzNjY2NDU0LTBiZWE2MWQxLTdhNWMtNGE5Ni1hMjQwLTU0MjMwYzUzYTVmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwMjE3MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2I0NDcxM2I3ODEwNDU4NWE1Y2ZiNDNhZmE2NzNlYWYwNTk0NGYzZmRiY2RiYjcyOTkzNDQxNzYwMzMxZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jujrN5bi_FMJ8LaNSZtKuR9f6SCxfNNdTiaJ6ngINOY) I also reverted to the main settings, but same error... however my prolific account is working correctly on chrome

UPDATE: i just deleted this directory and installed it again using git clone, but same error @tommyka1 @ShaggyBro @UnMars Please help

**Comment by noekun11** [comment] 2024-07-31 02:34
and also note that: the mail, pass are correct and im able to login them using edge broswer, and also able to see my funds and successfully withdraw them and also able to see and edit the messages to researchers.... i wonder what's wrong? did you guys encounter same problem? please help

**Comment by noekun11** [comment] 2024-07-31 04:31
> Probably same issue depicted here? #34 #35

bro.. you too getting the same error now?

**Closed** 2024-08-01 11:04 UTC

**Comment by SurfingTurtles** [comment] 2024-08-06 02:36
I'm stuck in this as well.. worked fine for a day and now this:

[+] Getting a new bearer token...
Driver started
Logging in...
[-] Failed to log in, retrying in 3s...
[+] Getting a new bearer token...
Driver started
Logging in...

**Comment by noekun11** [comment] 2024-08-06 02:44
> I'm stuck in this as well.. worked fine for a day and now this:
> 
> [+] Getting a new bearer token... Driver started Logging in... [-] Failed to log in, retrying in 3s... [+] Getting a new bearer token... Driver started Logging in...

You have to update the drivers.json everyday

**Comment by SurfingTurtles** [comment] 2024-08-06 02:49
> > I'm stuck in this as well.. worked fine for a day and now this:
> > [+] Getting a new bearer token... Driver started Logging in... [-] Failed to log in, retrying in 3s... [+] Getting a new bearer token... Driver started Logging in...
> 
> You have to update the drivers.json everyday

At the risk of sounding stupid - where would I find that? I'm on a Mac - and don't have a file on my system with that name.

**Comment by noekun11** [comment] 2024-08-06 02:58
Refer here for more info [#35](https://github.com/UnMars/Prolific-Joiner/issues/35)
And im not sure about the location which Mac stores by default, search for similar files in similar folders, you will get an answer.

**Comment by Gazzy88** [comment] 2024-08-08 05:19
Using scripts and still openly posting it on the internet is too childish. I don't use any script because I want to be a good user of the platform. Y'all are making it hard for researchers to get good data. Post like this is highly insensitive and can put many accounts on hold. Prolific is very strict on shady data.

**Comment by ShaggyBro** [comment] 2024-08-08 06:17
Sir.. this is a Wendy's.
I mean.. GitHub.

**Comment by frankmutinda** [comment] 2024-10-14 08:30
hello, how is it installed in chrome

**Comment by frankmutinda** [comment] 2024-10-14 10:31
> line 240 is the randomness (-5s/+5s), and on the config file the wait_time brother
hey man, How can I install the script in chrome
